name: bsteele_music_lib
description: backend Dart library for the bsteeleMusicApp, see bsteele.com
publish_to: none
# version: 1.0.0
# homepage: https://pub.dev/packages?q=

environment:
  sdk: ^3.11.0

dependencies:
  logger:
  quiver:
  archive:
  intl:
  string_similarity:
  meta:
  english_words:
  string_scanner:   # for english_words
  flutter_lints:
  dartdoc:
  csv: ^6.0.0     #  7.10 missing ListToCsvConverter
  xml:
  dotenv:
  tuple:
  collection:
  web_socket_channel:
  change_notifier:
  worker_manager:
  excel:
  http:

dev_dependencies:
  lints:
  test:
  build_runner:
  build_web_compilers:
  compute:
